//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class DVTDevice, DVTStackBacktrace, IDERunOperation, IDETestRunner, NSMutableArray, NSString;

@interface _IDETestResultsProcessor : NSObject
{
    BOOL _finished;
    IDETestRunner *_testRunner;
    NSString *_targetArchitecture;
    DVTDevice *_targetDevice;
    IDERunOperation *_operation;
    NSMutableArray *_validatorsStack;
}

+ (void)initialize;
@property(retain) NSMutableArray *validatorsStack; // @synthesize validatorsStack=_validatorsStack;
@property BOOL finished; // @synthesize finished=_finished;
@property(readonly) IDERunOperation *operation; // @synthesize operation=_operation;
@property(retain) DVTDevice *targetDevice; // @synthesize targetDevice=_targetDevice;
@property(retain) NSString *targetArchitecture; // @synthesize targetArchitecture=_targetArchitecture;
@property(retain) IDETestRunner *testRunner; // @synthesize testRunner=_testRunner;

- (BOOL)validateEvent:(int)arg1 error:(id *)arg2;
- (void)initializeValidatorsStack;
- (id)initWithTestRunOperation:(id)arg1 forTestRunner:(id)arg2;
- (void)primitiveInvalidate;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

