//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTFoundation/DTDKCertificateService.h>

@interface DTDKRevokeCertService : DTDKCertificateService
{
}

+ (id)serviceForCertificateType:(unsigned long long)arg1 team:(id)arg2 platform:(id)arg3 andSerialNumber:(id)arg4;

@end

