//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTFoundation/DVTPortalOperation.h>

@interface DVTAddAppIDOperation : DVTPortalOperation
{
}

+ (id)operationWithSingleTeamToken:(id)arg1 name:(id)arg2 andPlatform:(id)arg3;
+ (id)operationWithSingleTeamToken:(id)arg1 name:(id)arg2 bundleIdentifier:(id)arg3 andPlatform:(id)arg4;
+ (id)operationWithSingleTeamToken:(id)arg1 name:(id)arg2 prefix:(id)arg3 bundleIdentifier:(id)arg4 andPlatform:(id)arg5;

@end

