//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTFoundation/DVTPortalOperation.h>

@interface DVTAddDeviceOperation : DVTPortalOperation
{
}

+ (id)operationWithSingleTeamToken:(id)arg1 UUID:(id)arg2 name:(id)arg3 andPlatform:(id)arg4;
- (void)_failure:(id)arg1;

@end

