//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DVTDTApplicationWorkspaceClient.h"

@class NSMapTable, NSString;

@interface DVTAppExtensionInstallPromiseManager : NSObject <DVTDTApplicationWorkspaceClient>
{
    NSMapTable *_promiseMap;
}

+ (BOOL)listenForIDs:(id)arg1 promise:(id)arg2 channel:(id)arg3;
+ (void)initialize;
- (void).cxx_destruct;
- (void)applicationUninstalled:(id)arg1;
- (void)applicationInstalled:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

