//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTFoundation/DVTDeveloperAccount.h>

@interface DVTCertBasedDeveloperAccount : DVTDeveloperAccount
{
    struct OpaqueSecIdentityRef *_identity;
}

+ (id)accountWithIdentity:(struct OpaqueSecIdentityRef *)arg1;
- (id)_sessionByLoggingIn:(id *)arg1;
- (_Bool)isCertBased;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (struct OpaqueSecIdentityRef *)identity;
- (void)dealloc;

@end

