//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol DVTCodesignableDevice <NSObject>
@property(readonly, copy, nonatomic) NSString *name;
@property(readonly, copy, nonatomic) NSString *deviceIdentifier;
@property(readonly, copy, nonatomic) NSString *platformIdentifier;
@property(readonly, nonatomic) BOOL supportsProvisioning;
@end

