//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DVTDeveloperProfile : NSObject
{
}

+ (id)currentProfile;
- (void)syncCertificatesForAccount:(id)arg1 statusHandler:(CDUnknownBlockType)arg2;

@end

