//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet, NSString;

@protocol DVTDeviceApplicationItem <NSObject>
@property(readonly) BOOL isLeaf;
@property(readonly) NSSet *children;
@property(readonly) NSString *name;

@optional
@property(readonly, copy) NSString *installedPath;
@end

