//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTFoundation/DVTPortalOperation.h>

@interface DVTDownloadProfileOperation : DVTPortalOperation
{
}

+ (id)operationWithSingleTeamToken:(id)arg1 appIdId:(id)arg2 andPlatform:(id)arg3;
+ (id)operationWithSingleTeamToken:(id)arg1 profileIds:(id)arg2 andPlatform:(id)arg3;
+ (id)operationWithSingleTeamToken:(id)arg1 profileId:(id)arg2 andPlatform:(id)arg3;
- (_Bool)_shouldRetryOnServiceError:(id)arg1;

@end

