//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DVTDeviceApplication.h"

@class NSSet, NSString;

@interface DVTDeviceApplicationBase : NSObject <DVTDeviceApplication>
{
    BOOL _isFairPlayEncrypted;
    BOOL _isLeaf;
    BOOL _isHidden;
    NSString *_name;
    NSString *_version;
    NSString *_bundleIdentifier;
    NSSet *_children;
    NSSet *_rootContainerApplicationItems;
    NSString *_installedPath;
}

@property(copy) NSString *installedPath; // @synthesize installedPath=_installedPath;
@property BOOL isHidden; // @synthesize isHidden=_isHidden;
@property BOOL isLeaf; // @synthesize isLeaf=_isLeaf;
@property(retain) NSSet *rootContainerApplicationItems; // @synthesize rootContainerApplicationItems=_rootContainerApplicationItems;
@property(retain) NSSet *children; // @synthesize children=_children;
@property BOOL isFairPlayEncrypted; // @synthesize isFairPlayEncrypted=_isFairPlayEncrypted;
@property(retain) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(retain) NSString *version; // @synthesize version=_version;
@property(retain) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

