//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTFoundation/DVTPrimitiveFileDataType.h>

@interface DVTDeclaredPrimitiveFileDataType : DVTPrimitiveFileDataType
{
}

- (BOOL)isDeclaredType;
- (id)initWithIdentifier:(id)arg1 displayName:(id)arg2 conformingToTypes:(id)arg3;

@end

