//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMapTable, NSMutableSet, NSObject<OS_dispatch_queue>;

@interface DVTFilePathEventWatcher : NSObject
{
    struct __FSEventStream *_streamRef;
    NSObject<OS_dispatch_queue> *_watcherQueue;
    double _latency;
    unsigned long long _lastEventHandled;
    NSMutableSet *_watchedFilePaths;
    NSMapTable *_watchedFileMap;
}

+ (id)sharedFilePathEventWatcher;
+ (void)initialize;
- (void).cxx_destruct;
- (void)handleEventsForStream:(struct __FSEventStream *)arg1 numEvents:(unsigned long long)arg2 eventPaths:(const char **)arg3 eventFlags:(const unsigned int *)arg4 eventIds:(const unsigned long long *)arg5;
- (void)stop;
- (void)run;
- (void)_resetStream;
- (void)_teardownStream;
- (void)_setupStream;
- (void)watchFilePath:(id)arg1;
- (BOOL)_shouldWatchWholeVolumes;
@property double eventLatency;
- (void)dealloc;
- (id)init;
- (id)_initPrivate;

@end

