//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DVTDispatchLock, DVTRegularExpression, NSArray;

@interface DVTKVCMethodStyle : NSObject
{
    int mask;
    unsigned long long numSubexpressions;
    DVTRegularExpression *regex;
    DVTDispatchLock *regexLock;
    NSArray *patterns;
}

@property(readonly) NSArray *patterns; // @synthesize patterns;
@property(readonly) DVTDispatchLock *regexLock; // @synthesize regexLock;
@property(readonly) DVTRegularExpression *regex; // @synthesize regex;
@property(readonly) unsigned long long numSubexpressions; // @synthesize numSubexpressions;
@property(readonly) int mask; // @synthesize mask;
- (void).cxx_destruct;
- (id)initWithMask:(int)arg1 numSubexpressions:(unsigned long long)arg2 regex:(id)arg3 patterns:(id)arg4;

@end

