//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface DVTMacroExpansionIntegerMetric : NSObject
{
    NSString *_label;
    unsigned long long *_sampleCounts;
    struct _NSRange _valueRange;
}

@property(readonly) unsigned long long *sampleCounts; // @synthesize sampleCounts=_sampleCounts;
@property(readonly) struct _NSRange valueRange; // @synthesize valueRange=_valueRange;
@property(readonly) NSString *label; // @synthesize label=_label;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)longDescription;
- (void)addValue:(unsigned long long)arg1;
- (void)dealloc;
- (id)initWithLabel:(id)arg1 valueRange:(struct _NSRange)arg2;

@end

