//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DVTMapTable, NSString;

@interface DVTMountedFileSystem : NSObject
{
    int _deviceNumber;
    NSString *_mountPath;
    DVTMapTable *_inodesToVNodes;
}

+ (id)mountedFileSystemWithDeviceNumber:(int)arg1;
@property(readonly) NSString *mountPath; // @synthesize mountPath=_mountPath;
@property(readonly) int deviceNumber; // @synthesize deviceNumber=_deviceNumber;
- (void).cxx_destruct;
- (id)description;
- (void)removeVNode:(id)arg1;
- (void)addVNode:(id)arg1;
- (void)noteFileSystemWasUnmounted;
- (id)vnodeForInodeNumber:(unsigned long long)arg1;
- (id)initWithDeviceNumber:(int)arg1 statfsInfo:(const struct statfs *)arg2;

@end

