//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTFoundation/DVTPortalOperation.h>

@interface DVTRevokeCertificateOperation : DVTPortalOperation
{
}

+ (id)operationWithSingleTeamToken:(id)arg1 certificateType:(unsigned long long)arg2 andPlatform:(id)arg3 serialNumber:(id)arg4;

@end

