//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DVTVersion, NSArray, NSString;

@protocol DVTRegistrable <NSObject>
@property(readonly) NSString *identifier;

@optional
@property(readonly) NSString *displayDescription;
@property(readonly) NSString *displayName;
@property(readonly) DVTVersion *version;
@property(readonly) NSArray *aliases;
@end

