//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DVTSigningCertificate, DVTSigningCertificateSource;

@protocol DVTSigningCertificateSourceDelegate <NSObject>
- (void)signingCertificateSourceShouldDoFullResetFromSigningCertificates:(DVTSigningCertificateSource *)arg1;
- (void)signingCertificateSourcePrivateKeyStatusForCertificatesMayHaveChanged:(DVTSigningCertificateSource *)arg1;
- (void)signingCertificateSource:(DVTSigningCertificateSource *)arg1 didRemoveCertificate:(DVTSigningCertificate *)arg2;
- (void)signingCertificateSource:(DVTSigningCertificateSource *)arg1 didAddCertificate:(DVTSigningCertificate *)arg2;
@end

