//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTFoundation/DVTObservingToken.h>

@class DVTWeakInterposer, NSString;

@interface DVTSelectorBasedObservingToken : DVTObservingToken
{
    DVTWeakInterposer *_target_dvtWeakInterposer;
    id _observedObject;
    NSString *_keyPath;
}

@property(retain) id observedObject; // @synthesize observedObject=_observedObject;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)_primitiveCancelObservation;
- (id)description;
- (id)initWithTarget:(id)arg1 observedObject:(id)arg2 keyPath:(id)arg3;
- (void)setTarget:(id)arg1;
- (id)target;

@end

