//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DVTSourceScanner, NSSet;

@interface DVTScannerRule : NSObject
{
    long long _token;
    NSSet *_tokenSet;
    BOOL _optional;
    BOOL _allowMultiple;
    DVTSourceScanner *_scanner;
}

@property(readonly) DVTSourceScanner *scanner; // @synthesize scanner=_scanner;
@property(readonly) BOOL allowMultiple; // @synthesize allowMultiple=_allowMultiple;
@property(readonly) BOOL optional; // @synthesize optional=_optional;
- (void).cxx_destruct;
- (BOOL)matchesToken:(long long)arg1;
- (id)initWithString:(id)arg1;

@end

