//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTFoundation/DVTPortalOperation.h>

@interface DVTUpdatePortalDatabaseOperation : DVTPortalOperation
{
}

+ (id)operationWithDependency:(id)arg1;
+ (id)operationWithDependencies:(id)arg1;
+ (id)operationWithToken:(id)arg1 dependencies:(id)arg2;
+ (id)operation;

@end

