//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DVTXMLUnarchiver;

@protocol DVTXMLUnarchiving <NSObject>
- (id)initFromXMLUnarchiver:(DVTXMLUnarchiver *)arg1 archiveVersion:(float)arg2;
@end

