//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (DVTFoundationClassAdditions)
- (id)dvt_dateStringRelativeToTodayWithDateStyle:(unsigned long long)arg1 timeStyle:(unsigned long long)arg2;
@end

