//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSMutableData.h"

@interface NSMutableData (DVTFoundationClassAdditions)
- (void)dvt_appendMD5DigestOfData:(id)arg1;
- (void)dvt_appendMD5DigestOfBytes:(const void *)arg1 length:(unsigned long long)arg2;
@end

