//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOutputStream.h"

@interface NSOutputStream (DVTFoundationClassAdditions)
- (void)dvt_writeSignedLEB128Integer:(long long)arg1;
- (void)dvt_writeUnsignedLEB128Integer:(unsigned long long)arg1;
@end

