//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSValue.h"

@interface NSValue (DVTGeometryAdditions)
- (CDStruct_d2b197d1)dvt_insetValue;
@end

