//
//     Generated by class-dump 3.5 (64 bit)
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#pragma mark Blocks

typedef void (^CDUnknownBlockType)(void); // return type and parameters are unknown

#pragma mark Named Structures

struct PurpleFBMessage {
    struct {
        unsigned int _field1;
        unsigned int _field2;
        unsigned int _field3;
        unsigned int _field4;
        unsigned int _field5;
        int _field6;
    } _field1;
    struct {
        unsigned int _field1;
    } _field2;
    union {
        struct {
            CDStruct_1ede1e67 _field1;
            int _field2;
            int _field3;
            int _field4;
            int _field5;
            int _field6;
            int _field7;
        } _field1;
        struct {
            CDStruct_1ede1e67 _field1;
            int _field2;
            int _field3;
            int _field4;
            int _field5;
            int _field6;
            int _field7;
            int _field8;
            int _field9;
        } _field2;
        struct {
            unsigned char _field1[12];
            int _field2;
            int _field3;
            int _field4;
            int _field5;
        } _field3;
        struct {
            union {
                CDStruct_1ede1e67 _field1;
                CDStruct_72af3c3a _field2;
                CDStruct_72af3c3a _field3;
                struct {
                    unsigned int _field1;
                    unsigned int _field2;
                    unsigned int :24;
                    unsigned int :8;
                } _field4;
            } _field1;
        } _field4;
    } _field3;
};

#pragma mark Typedef'd Structures

typedef struct {
    unsigned int _field1;
    unsigned int _field2;
    unsigned int :16;
    unsigned int :8;
    unsigned int :8;
} CDStruct_1ede1e67;

typedef struct {
    void *_field1;
    unsigned int :8;
    unsigned int :8;
    unsigned int :8;
    unsigned int :8;
    unsigned int _field2;
} CDStruct_72af3c3a;

