//
//     Generated by class-dump 3.5 (64 bit)
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (SimulatorKitNSErrorAdditions)
+ (id)simkit_errorWithLocalizedDescription:(id)arg1 failureReason:(id)arg2;
+ (id)simkit_errorWithLocalizedDescriptionFormat:(id)arg1;
+ (id)simkit_errorWithLocalizedDescription:(id)arg1;
+ (id)simkit_errorWithUnderlyingError:(id)arg1 localizedDescriptionFormat:(id)arg2;
+ (id)simkit_errorWithUnderlyingError:(id)arg1 localizedDescription:(id)arg2;
+ (id)simkit_errorWithUnderlyingError:(id)arg1 localizedDescription:(id)arg2 failureReason:(id)arg3;
@end

