//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSValue.h>

@interface NSValue (CoreMedia)
+ (id)valueWithCMTime:(CDStruct_1b6d18a9)arg1;
- (CDStruct_1b6d18a9)cmTime;
@end
