#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef FBDEVICECONTROL_SWIFT_H
#define FBDEVICECONTROL_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FBDeviceControl",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreMedia;
@import Darwin;
@import Dispatch;
@import FBControlCore;
@import Foundation;
@import ObjectiveC;
@import _DarwinFoundation2.netinet_in.in_port_t;
#endif

#import <FBDeviceControl/FBDeviceControl.h>

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FBDeviceControl",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class FBAMDevice;
@class NSNumber;
@class NSString;
@class FBAFCConnection;
SWIFT_CLASS_NAMED("FBAMDeviceServiceManager")
@interface FBAMDeviceServiceManager : NSObject
+ (FBAMDeviceServiceManager * _Nonnull)managerWithAMDevice:(FBAMDevice * _Nonnull)device serviceTimeout:(NSNumber * _Nullable)serviceTimeout SWIFT_WARN_UNUSED_RESULT;
- (FBFutureContextManager<FBAFCConnection *> * _Nonnull)houseArrestAFCConnectionForBundleID:(NSString * _Nonnull)bundleID afcCalls:(AFCCalls)afcCalls SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FBDevice;
@class NSNull;
SWIFT_CLASS("_TtC15FBDeviceControl31FBAppleDevicectlCommandExecutor")
@interface FBAppleDevicectlCommandExecutor : NSObject
- (nonnull instancetype)initWithDevice:(FBDevice * _Nonnull)device OBJC_DESIGNATED_INITIALIZER;
- (FBProcessBuilder<NSNull *, NSString *, NSString *> * _Nonnull)taskBuilderWithArguments:(NSArray<NSString *> * _Nonnull)arguments SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FBApplicationLaunchConfiguration;
@interface FBAppleDevicectlCommandExecutor (SWIFT_EXTENSION(FBDeviceControl))
- (FBFuture<NSNumber *> * _Nonnull)launchApplicationWithConfiguration:(FBApplicationLaunchConfiguration * _Nonnull)configuration SWIFT_WARN_UNUSED_RESULT;
@end

@class FBDeveloperDiskImage;
@interface FBDevice (SWIFT_EXTENSION(FBDeviceControl))
- (FBFuture<FBDeveloperDiskImage *> * _Nonnull)ensureDeveloperDiskImageIsMounted SWIFT_WARN_UNUSED_RESULT;
@end

@protocol FBiOSTarget;
SWIFT_CLASS("_TtC15FBDeviceControl26FBDeviceActivationCommands")
@interface FBDeviceActivationCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl27FBDeviceApplicationCommands")
@interface FBDeviceApplicationCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_RESILIENT_CLASS_NAMED("FBDeviceControlError")
@interface FBDeviceControlError : FBControlCoreError
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSPredicate;
@class FBCrashLogInfo;
SWIFT_CLASS("_TtC15FBDeviceControl24FBDeviceCrashLogCommands")
@interface FBDeviceCrashLogCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<FBCrashLogInfo *> * _Nonnull)notifyOfCrash:(NSPredicate * _Nonnull)predicate SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FBAMDServiceConnection;
@protocol FBControlCoreLogger;
@class FBSocketServer;
SWIFT_CLASS_NAMED("FBDeviceDebugServer")
@interface FBDeviceDebugServer : NSObject <FBSocketServerDelegate>
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull lldbBootstrapCommands;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull queue;
/// Factory method: creates and starts a debug server from a future-wrapped service connection.
+ (FBFuture<id> * _Nonnull)debugServerForServiceConnection:(FBFutureContext<FBAMDServiceConnection *> * _Nonnull)service port:(in_port_t)port lldbBootstrapCommands:(NSArray<NSString *> * _Nonnull)lldbBootstrapCommands queue:(dispatch_queue_t _Nonnull)queue logger:(id <FBControlCoreLogger> _Nonnull)logger SWIFT_WARN_UNUSED_RESULT;
- (void)socketServer:(FBSocketServer * _Nonnull)server clientConnected:(struct in6_addr)address fileDescriptor:(int32_t)fileDescriptor;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl24FBDeviceDebuggerCommands")
@interface FBDeviceDebuggerCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl34FBDeviceDeveloperDiskImageCommands")
@interface FBDeviceDeveloperDiskImageCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl37FBDeviceDiagnosticInformationCommands")
@interface FBDeviceDiagnosticInformationCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl21FBDeviceEraseCommands")
@interface FBDeviceEraseCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl20FBDeviceFileCommands")
@interface FBDeviceFileCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBDeviceFileContainer")
@interface FBDeviceFileContainer : NSObject
- (nonnull instancetype)initWithAfcConnection:(FBAFCConnection * _Nonnull)connection queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl25FBDeviceLifecycleCommands")
@interface FBDeviceLifecycleCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBDeviceLinkClient")
@interface FBDeviceLinkClient : NSObject
+ (FBFuture<FBDeviceLinkClient *> * _Nonnull)deviceLinkClientWithConnection:(FBAMDServiceConnection * _Nonnull)connection SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl24FBDeviceLocationCommands")
@interface FBDeviceLocationCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl19FBDeviceLogCommands")
@interface FBDeviceLogCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBDeviceLogOperation")
@interface FBDeviceLogOperation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl21FBDevicePowerCommands")
@interface FBDevicePowerCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl35FBDeviceProvisioningProfileCommands")
@interface FBDeviceProvisioningProfileCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl24FBDeviceRecoveryCommands")
@interface FBDeviceRecoveryCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl26FBDeviceScreenshotCommands")
@interface FBDeviceScreenshotCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol FBiOSTargetInfo;
SWIFT_CLASS_NAMED("FBDeviceSet")
@interface FBDeviceSet : NSObject <FBiOSTargetSet, FBiOSTargetSetDelegate>
@property (nonatomic, readonly, strong) id <FBControlCoreLogger> _Nonnull logger;
@property (nonatomic, weak) id <FBiOSTargetSetDelegate> _Nullable delegate;
- (nullable instancetype)setWithLogger:(id <FBControlCoreLogger> _Nonnull)logger delegate:(id <FBiOSTargetSetDelegate> _Nullable)delegate ecidFilter:(NSString * _Nullable)ecidFilter error:(NSError * _Nullable * _Nullable)error SWIFT_METHOD_FAMILY(init);
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (id <FBiOSTargetInfo> _Nullable)targetWithUDID:(NSString * _Nonnull)udid SWIFT_WARN_UNUSED_RESULT;
- (FBDevice * _Nullable)deviceWithUDID:(NSString * _Nonnull)udid SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray<id <FBiOSTargetInfo>> * _Nonnull allTargetInfos;
@property (nonatomic, readonly, copy) NSArray<FBDevice *> * _Nonnull allDevices;
- (void)targetAdded:(id <FBiOSTargetInfo> _Nonnull)targetInfo inTargetSet:(id <FBiOSTargetSet> _Nonnull)targetSet;
- (void)targetRemoved:(id <FBiOSTargetInfo> _Nonnull)targetInfo inTargetSet:(id <FBiOSTargetSet> _Nonnull)targetSet;
- (void)targetUpdated:(id <FBiOSTargetInfo> _Nonnull)targetInfo inTargetSet:(id <FBiOSTargetSet> _Nonnull)targetSet;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl32FBDeviceSocketForwardingCommands")
@interface FBDeviceSocketForwardingCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl30FBDeviceVideoRecordingCommands")
@interface FBDeviceVideoRecordingCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AVCaptureSession;
@class FBVideoStreamConfiguration;
@protocol FBDataConsumer;
SWIFT_CLASS_NAMED("FBDeviceVideoStream")
@interface FBDeviceVideoStream : NSObject
+ (FBDeviceVideoStream * _Nullable)streamWithSession:(AVCaptureSession * _Nonnull)session configuration:(FBVideoStreamConfiguration * _Nonnull)configuration logger:(id <FBControlCoreLogger> _Nonnull)logger error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNull *> * _Nonnull)startStreaming:(id <FBDataConsumer> _Nonnull)consumer SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNull *> * _Nonnull)stopStreaming SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) FBFuture<NSNull *> * _Nonnull completed;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AVCaptureOutput;
@class AVCaptureConnection;
@interface FBDeviceVideoStream (SWIFT_EXTENSION(FBDeviceControl)) <AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didDropSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

SWIFT_CLASS("_TtC15FBDeviceControl22FBDeviceXCTestCommands")
@interface FBDeviceXCTestCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDictionary;
@class NSData;
SWIFT_CLASS_NAMED("FBManagedConfigClient")
@interface FBManagedConfigClient : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull serviceName;)
+ (NSString * _Nonnull)serviceName SWIFT_WARN_UNUSED_RESULT;
+ (FBManagedConfigClient * _Nonnull)managedConfigClientWithConnection:(FBAMDServiceConnection * _Nonnull)connection logger:(id <FBControlCoreLogger> _Nonnull)logger SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSDictionary *> * _Nonnull)getCloudConfiguration SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNull *> * _Nonnull)changeWallpaperWithName:(NSString * _Nonnull)name data:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSArray *> * _Nonnull)getProfileList SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSDictionary *> * _Nonnull)installProfile:(NSData * _Nonnull)payload SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNull *> * _Nonnull)removeProfile:(NSString * _Nonnull)profileName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBSpringboardServicesClient")
@interface FBSpringboardServicesClient : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull wallpaperNameHomescreen;)
+ (NSString * _Nonnull)wallpaperNameHomescreen SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull wallpaperNameLockscreen;)
+ (NSString * _Nonnull)wallpaperNameLockscreen SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull serviceName;)
+ (NSString * _Nonnull)serviceName SWIFT_WARN_UNUSED_RESULT;
+ (FBSpringboardServicesClient * _Nonnull)springboardServicesClientWithConnection:(FBAMDServiceConnection * _Nonnull)connection logger:(id <FBControlCoreLogger> _Nonnull)logger SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConnection:(FBAMDServiceConnection * _Nonnull)connection logger:(id <FBControlCoreLogger> _Nonnull)logger;
- (FBFuture<NSData *> * _Nonnull)wallpaperImageDataForKind:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("_FBDeviceStorageBase")
@interface FBDeviceStorage : NSObject
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull attached;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull referenced;
- (nonnull instancetype)initWithLogger:(id <FBControlCoreLogger> _Nonnull)logger OBJC_DESIGNATED_INITIALIZER;
- (void)deviceAttached:(id _Nonnull)device forKey:(NSString * _Nonnull)key;
- (void)deviceDetachedForKey:(NSString * _Nonnull)key;
- (id _Nullable)deviceForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
#ifndef FBDEVICECONTROL_SWIFT_H
#define FBDEVICECONTROL_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FBDeviceControl",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreMedia;
@import Darwin;
@import Dispatch;
@import FBControlCore;
@import Foundation;
@import ObjectiveC;
@import _DarwinFoundation2.netinet_in.in_port_t;
#endif

#import <FBDeviceControl/FBDeviceControl.h>

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="FBDeviceControl",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class FBAMDevice;
@class NSNumber;
@class NSString;
@class FBAFCConnection;
SWIFT_CLASS_NAMED("FBAMDeviceServiceManager")
@interface FBAMDeviceServiceManager : NSObject
+ (FBAMDeviceServiceManager * _Nonnull)managerWithAMDevice:(FBAMDevice * _Nonnull)device serviceTimeout:(NSNumber * _Nullable)serviceTimeout SWIFT_WARN_UNUSED_RESULT;
- (FBFutureContextManager<FBAFCConnection *> * _Nonnull)houseArrestAFCConnectionForBundleID:(NSString * _Nonnull)bundleID afcCalls:(AFCCalls)afcCalls SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FBDevice;
@class NSNull;
SWIFT_CLASS("_TtC15FBDeviceControl31FBAppleDevicectlCommandExecutor")
@interface FBAppleDevicectlCommandExecutor : NSObject
- (nonnull instancetype)initWithDevice:(FBDevice * _Nonnull)device OBJC_DESIGNATED_INITIALIZER;
- (FBProcessBuilder<NSNull *, NSString *, NSString *> * _Nonnull)taskBuilderWithArguments:(NSArray<NSString *> * _Nonnull)arguments SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FBApplicationLaunchConfiguration;
@interface FBAppleDevicectlCommandExecutor (SWIFT_EXTENSION(FBDeviceControl))
- (FBFuture<NSNumber *> * _Nonnull)launchApplicationWithConfiguration:(FBApplicationLaunchConfiguration * _Nonnull)configuration SWIFT_WARN_UNUSED_RESULT;
@end

@class FBDeveloperDiskImage;
@interface FBDevice (SWIFT_EXTENSION(FBDeviceControl))
- (FBFuture<FBDeveloperDiskImage *> * _Nonnull)ensureDeveloperDiskImageIsMounted SWIFT_WARN_UNUSED_RESULT;
@end

@protocol FBiOSTarget;
SWIFT_CLASS("_TtC15FBDeviceControl26FBDeviceActivationCommands")
@interface FBDeviceActivationCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl27FBDeviceApplicationCommands")
@interface FBDeviceApplicationCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_RESILIENT_CLASS_NAMED("FBDeviceControlError")
@interface FBDeviceControlError : FBControlCoreError
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSPredicate;
@class FBCrashLogInfo;
SWIFT_CLASS("_TtC15FBDeviceControl24FBDeviceCrashLogCommands")
@interface FBDeviceCrashLogCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<FBCrashLogInfo *> * _Nonnull)notifyOfCrash:(NSPredicate * _Nonnull)predicate SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class FBAMDServiceConnection;
@protocol FBControlCoreLogger;
@class FBSocketServer;
SWIFT_CLASS_NAMED("FBDeviceDebugServer")
@interface FBDeviceDebugServer : NSObject <FBSocketServerDelegate>
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull lldbBootstrapCommands;
@property (nonatomic, readonly, strong) dispatch_queue_t _Nonnull queue;
/// Factory method: creates and starts a debug server from a future-wrapped service connection.
+ (FBFuture<id> * _Nonnull)debugServerForServiceConnection:(FBFutureContext<FBAMDServiceConnection *> * _Nonnull)service port:(in_port_t)port lldbBootstrapCommands:(NSArray<NSString *> * _Nonnull)lldbBootstrapCommands queue:(dispatch_queue_t _Nonnull)queue logger:(id <FBControlCoreLogger> _Nonnull)logger SWIFT_WARN_UNUSED_RESULT;
- (void)socketServer:(FBSocketServer * _Nonnull)server clientConnected:(struct in6_addr)address fileDescriptor:(int32_t)fileDescriptor;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl24FBDeviceDebuggerCommands")
@interface FBDeviceDebuggerCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl34FBDeviceDeveloperDiskImageCommands")
@interface FBDeviceDeveloperDiskImageCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl37FBDeviceDiagnosticInformationCommands")
@interface FBDeviceDiagnosticInformationCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl21FBDeviceEraseCommands")
@interface FBDeviceEraseCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl20FBDeviceFileCommands")
@interface FBDeviceFileCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBDeviceFileContainer")
@interface FBDeviceFileContainer : NSObject
- (nonnull instancetype)initWithAfcConnection:(FBAFCConnection * _Nonnull)connection queue:(dispatch_queue_t _Nonnull)queue OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl25FBDeviceLifecycleCommands")
@interface FBDeviceLifecycleCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBDeviceLinkClient")
@interface FBDeviceLinkClient : NSObject
+ (FBFuture<FBDeviceLinkClient *> * _Nonnull)deviceLinkClientWithConnection:(FBAMDServiceConnection * _Nonnull)connection SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl24FBDeviceLocationCommands")
@interface FBDeviceLocationCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl19FBDeviceLogCommands")
@interface FBDeviceLogCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBDeviceLogOperation")
@interface FBDeviceLogOperation : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl21FBDevicePowerCommands")
@interface FBDevicePowerCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl35FBDeviceProvisioningProfileCommands")
@interface FBDeviceProvisioningProfileCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl24FBDeviceRecoveryCommands")
@interface FBDeviceRecoveryCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl26FBDeviceScreenshotCommands")
@interface FBDeviceScreenshotCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol FBiOSTargetInfo;
SWIFT_CLASS_NAMED("FBDeviceSet")
@interface FBDeviceSet : NSObject <FBiOSTargetSet, FBiOSTargetSetDelegate>
@property (nonatomic, readonly, strong) id <FBControlCoreLogger> _Nonnull logger;
@property (nonatomic, weak) id <FBiOSTargetSetDelegate> _Nullable delegate;
- (nullable instancetype)setWithLogger:(id <FBControlCoreLogger> _Nonnull)logger delegate:(id <FBiOSTargetSetDelegate> _Nullable)delegate ecidFilter:(NSString * _Nullable)ecidFilter error:(NSError * _Nullable * _Nullable)error SWIFT_METHOD_FAMILY(init);
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (id <FBiOSTargetInfo> _Nullable)targetWithUDID:(NSString * _Nonnull)udid SWIFT_WARN_UNUSED_RESULT;
- (FBDevice * _Nullable)deviceWithUDID:(NSString * _Nonnull)udid SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSArray<id <FBiOSTargetInfo>> * _Nonnull allTargetInfos;
@property (nonatomic, readonly, copy) NSArray<FBDevice *> * _Nonnull allDevices;
- (void)targetAdded:(id <FBiOSTargetInfo> _Nonnull)targetInfo inTargetSet:(id <FBiOSTargetSet> _Nonnull)targetSet;
- (void)targetRemoved:(id <FBiOSTargetInfo> _Nonnull)targetInfo inTargetSet:(id <FBiOSTargetSet> _Nonnull)targetSet;
- (void)targetUpdated:(id <FBiOSTargetInfo> _Nonnull)targetInfo inTargetSet:(id <FBiOSTargetSet> _Nonnull)targetSet;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl32FBDeviceSocketForwardingCommands")
@interface FBDeviceSocketForwardingCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC15FBDeviceControl30FBDeviceVideoRecordingCommands")
@interface FBDeviceVideoRecordingCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AVCaptureSession;
@class FBVideoStreamConfiguration;
@protocol FBDataConsumer;
SWIFT_CLASS_NAMED("FBDeviceVideoStream")
@interface FBDeviceVideoStream : NSObject
+ (FBDeviceVideoStream * _Nullable)streamWithSession:(AVCaptureSession * _Nonnull)session configuration:(FBVideoStreamConfiguration * _Nonnull)configuration logger:(id <FBControlCoreLogger> _Nonnull)logger error:(NSError * _Nullable * _Nullable)error SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNull *> * _Nonnull)startStreaming:(id <FBDataConsumer> _Nonnull)consumer SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNull *> * _Nonnull)stopStreaming SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) FBFuture<NSNull *> * _Nonnull completed;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class AVCaptureOutput;
@class AVCaptureConnection;
@interface FBDeviceVideoStream (SWIFT_EXTENSION(FBDeviceControl)) <AVCaptureVideoDataOutputSampleBufferDelegate>
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didDropSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
@end

SWIFT_CLASS("_TtC15FBDeviceControl22FBDeviceXCTestCommands")
@interface FBDeviceXCTestCommands : NSObject <FBiOSTargetCommand>
+ (nonnull instancetype)commandsWithTarget:(id <FBiOSTarget> _Nonnull)target SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDictionary;
@class NSData;
SWIFT_CLASS_NAMED("FBManagedConfigClient")
@interface FBManagedConfigClient : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull serviceName;)
+ (NSString * _Nonnull)serviceName SWIFT_WARN_UNUSED_RESULT;
+ (FBManagedConfigClient * _Nonnull)managedConfigClientWithConnection:(FBAMDServiceConnection * _Nonnull)connection logger:(id <FBControlCoreLogger> _Nonnull)logger SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSDictionary *> * _Nonnull)getCloudConfiguration SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNull *> * _Nonnull)changeWallpaperWithName:(NSString * _Nonnull)name data:(NSData * _Nonnull)data SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSArray *> * _Nonnull)getProfileList SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSDictionary *> * _Nonnull)installProfile:(NSData * _Nonnull)payload SWIFT_WARN_UNUSED_RESULT;
- (FBFuture<NSNull *> * _Nonnull)removeProfile:(NSString * _Nonnull)profileName SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("FBSpringboardServicesClient")
@interface FBSpringboardServicesClient : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull wallpaperNameHomescreen;)
+ (NSString * _Nonnull)wallpaperNameHomescreen SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull wallpaperNameLockscreen;)
+ (NSString * _Nonnull)wallpaperNameLockscreen SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull serviceName;)
+ (NSString * _Nonnull)serviceName SWIFT_WARN_UNUSED_RESULT;
+ (FBSpringboardServicesClient * _Nonnull)springboardServicesClientWithConnection:(FBAMDServiceConnection * _Nonnull)connection logger:(id <FBControlCoreLogger> _Nonnull)logger SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithConnection:(FBAMDServiceConnection * _Nonnull)connection logger:(id <FBControlCoreLogger> _Nonnull)logger;
- (FBFuture<NSData *> * _Nonnull)wallpaperImageDataForKind:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS_NAMED("_FBDeviceStorageBase")
@interface FBDeviceStorage : NSObject
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull attached;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull referenced;
- (nonnull instancetype)initWithLogger:(id <FBControlCoreLogger> _Nonnull)logger OBJC_DESIGNATED_INITIALIZER;
- (void)deviceAttached:(id _Nonnull)device forKey:(NSString * _Nonnull)key;
- (void)deviceDetachedForKey:(NSString * _Nonnull)key;
- (id _Nullable)deviceForKey:(NSString * _Nonnull)key SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
