//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class AXPTranslationObject;

@protocol AXPTranslationRuntimeHelper <NSObject>

@optional

- (void)handleNotification:(unsigned long long)arg1 data:(id<NSObject, NSCopying, NSSecureCoding>)arg2 associatedObject:(AXPTranslationObject *)arg3;

@end

