//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface _MDKLocalizationHelper : NSObject
{
    NSDictionary *mEnglishStringByKey;
    NSString *mTable;
}

- (void).cxx_destruct;
- (id)initWithTable:(id)arg1;
- (id)stringsForKey:(id)arg1 arguments:(struct __va_list_tag [1])arg2;

@end

