//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MobileDeviceKit/MDKAFCOperation.h>

@interface MDKAFCRenamePathOperation : MDKAFCOperation
{
}

- (id)initWithSourcePath:(id)arg1 toDestinationPath:(id)arg2;

@end

