//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MDKATHostConnection : NSObject
{
    void *mHostConnectionRef;
}

+ (void)initialize;
- (void)invalidate;
- (id)readMessage;
- (void)sendMessage:(id)arg1;
- (void)sendPong;
- (void)sendPing;
- (void)sendStatusMessage:(id)arg1;
- (void)sendAssetMetricsRequestWithDataClasses:(id)arg1;
- (void)sendSyncFailedWithErrorCode:(int)arg1;
- (void)sendFileErrorForAssetID:(id)arg1 dataClass:(id)arg2 errorCode:(int)arg3;
- (void)sendFileProgressForAssetID:(id)arg1 dataClass:(id)arg2 progress:(double)arg3 overallProgress:(double)arg4;
- (void)sendFileBeginForAssetID:(id)arg1 dataClass:(id)arg2 fileSize:(unsigned long long)arg3 totalBytes:(unsigned long long)arg4;
- (void)sendFileCompletedForAssetID:(id)arg1 dataClass:(id)arg2 assetPath:(id)arg3 metadata:(id)arg4 newAnchor:(id)arg5;
- (void)sendFileCompletedForAssetID:(id)arg1 dataClass:(id)arg2 assetPath:(id)arg3;
- (void)sendMetadataSyncFinishedWithSyncTypes:(id)arg1 newAnchors:(id)arg2 purgeableSize:(id)arg3;
- (void)sendSyncRequestWithDataClasses:(id)arg1 anchors:(id)arg2 hostInfo:(id)arg3;
- (id)description;
- (void)dealloc;
- (id)initWithDeviceUDID:(id)arg1 libraryIdentifier:(id)arg2;
- (id)initWithDeviceUDID:(id)arg1;
- (id)initWithConnectionRef:(void *)arg1;
- (unsigned long long)sessionNumber;
@property(readonly) unsigned long long grappaSessionID;

@end

