//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MDKAFCFileDescriptor : NSObject
{
    struct __AFCFileDescriptor *mFileDescriptorRef;
}

- (id)setImmutableOperationWithHint:(BOOL)arg1;
- (id)closeOperation;
- (id)unlockOperation;
- (id)lockOperationWithExclusivity:(BOOL)arg1;
- (id)setSizeOperationWithSize:(unsigned long long)arg1;
- (id)seekPositionOperation;
- (id)seekOperationWithPosition:(long long)arg1 direction:(unsigned long long)arg2;
- (id)writeOperationWithData:(id)arg1;
- (id)readOperationWithBuffer:(char *)arg1 length:(unsigned long long)arg2;
- (void)invalidate;
- (id)description;
- (void)dealloc;
- (id)initWithFileDescriptorRef:(struct __AFCFileDescriptor *)arg1;
@property(readonly, getter=isValid) BOOL valid;

@end

