//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol MDKMobileDeviceNotifierDelegate;

@interface MDKMobileDeviceNotifier : NSObject
{
    struct _AMDeviceNotificationContext *mNotificationSubscriptionRef;
    id <MDKMobileDeviceNotifierDelegate> _delegate;
}

@property __weak id <MDKMobileDeviceNotifierDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)delegateDidStop;
- (void)delegateWillStart;
- (void)delegateDidFailWithError:(id)arg1;
- (void)delegateDidDetachDevice:(id)arg1;
- (void)delegateDidAttachDevice:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

@end

