//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSNumber;

@interface MDKRestorableDevice : NSObject
{
    struct __AMRestorableDevice *mRestorableDeviceRef;
}

+ (BOOL)setLogFileURL:(id)arg1;
+ (void)enableLogStreaming:(BOOL)arg1;
+ (id)defaultRestoreOptions;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (void)dealloc;
- (id)initWithRestorableDeviceRef:(struct __AMRestorableDevice *)arg1;
- (void)startRestoreWithOptions:(id)arg1 delegate:(id)arg2;
- (id)copyMobileDevice;
- (id)lookupBoardConfigWithDeviceMap:(id)arg1;
- (BOOL)setLogFileURL:(id)arg1 logType:(id)arg2;
@property(readonly) NSNumber *locationID;
@property(readonly) NSNumber *ECID;
@property(readonly) NSNumber *productType;
@property(readonly) unsigned long long state;

@end

