//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MDKServiceConnection;

@interface MDKSyslogRelayService : NSObject
{
    MDKServiceConnection *mServiceConnection;
}

- (void).cxx_destruct;
- (id)readDataWithError:(id *)arg1;
- (id)newReadDispatchSourceWithQueue:(id)arg1;
- (void)invalidate;
- (void)dealloc;
- (id)initWithServiceConnection:(id)arg1;

@end

