//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MobileActivationError : NSObject
{
}

+ (id)errorWithString:(id)arg1 andFunctionLabel:(id)arg2 andFileLabel:(id)arg3 andLineNumber:(id)arg4 andErrorCode:(id)arg5 andUnderlyingError:(id)arg6;

@end

