//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class DTDKRemoteDeviceToken, DVTDispatchLock, NSString;
@protocol DTDKRemoteDeviceConsoleControllerDelegate;

@interface DTDKRemoteDeviceConsoleController : NSObject
{
    struct _AMDServiceConnection *_serviceRef;
    NSObject<OS_dispatch_queue> *_queue;
    NSObject<OS_dispatch_queue> *_socketQueue;
    NSObject<OS_dispatch_source> *_consoleSource;
    _Bool _isInvalidating;
    struct DTDKCircularBuffer *_circularBuffer;
    DVTDispatchLock *_bufferLock;
    id <DTDKRemoteDeviceConsoleControllerDelegate> _delegate;
    DTDKRemoteDeviceToken *_token;
}
@property __weak DTDKRemoteDeviceToken *token; // @synthesize token=_token;
@property(retain) id <DTDKRemoteDeviceConsoleControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy) NSString *consoleString;

+ (id)consoleStringWithData:(id)arg1 startingAtOffset:(unsigned long long)arg2;
+ (id)controllerForDevice:(id)arg1;
- (void)clear;
- (void)reload;
- (void)invalidate;
- (void)dealloc;

@end

