//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <DVTiPhoneSimulatorRemoteClient/DTiPhoneSimulatorApplicationSpecifier.h>

@class NSString;

@interface DTiPhoneSimulatorApplicationSpecifier_Path : DTiPhoneSimulatorApplicationSpecifier
{
    NSString *_appPath;
}

+ (id)specifierWithApplicationPath:(id)arg1;
- (id)appPath;
- (void).cxx_destruct;
- (id)description;

@end

