//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov 22 2016 05:57:16).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class DVTXMLUnarchiver;

@protocol DVTXMLUnarchiving <NSObject>
- (id)initFromXMLUnarchiver:(DVTXMLUnarchiver *)arg1 archiveVersion:(float)arg2;
@end

