/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import <Foundation/Foundation.h>

#import <FBControlCore/FBArchitecture.h>

/**
 Uses the known values of SimDeviceType ProductFamilyID, to construct an enumeration.
 These mirror the values from -[SimDeviceState productFamilyID].
 */
typedef NS_ENUM(NSUInteger, FBControlCoreProductFamily) {
  FBControlCoreProductFamilyUnknown = 0,
  FBControlCoreProductFamilyiPhone = 1,
  FBControlCoreProductFamilyiPad = 2,
  FBControlCoreProductFamilyAppleTV = 3,
  FBControlCoreProductFamilyAppleWatch = 4,
  FBControlCoreProductFamilyMac = 5,
};

/**
 Device Names Enumeration.
 */
typedef NSString *FBDeviceModel NS_STRING_ENUM;

extern FBDeviceModel _Nonnull const FBDeviceModeliPhone4s;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone5;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone5c;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone5s;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone6;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone6Plus;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone6S;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone6SPlus;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhoneSE_1stGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhoneSE_2ndGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone7;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone7Plus;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone8;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone8Plus;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhoneX;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhoneXs;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhoneXsMax;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhoneXr;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone11;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone11Pro;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone11ProMax;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone12mini;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone12;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone12Pro;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone12ProMax;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone13mini;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone13;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone13Pro;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone13ProMax;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone14;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone14Plus;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone14Pro;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone14ProMax;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone15;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone15Plus;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone15Pro;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone15ProMax;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone16;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone16Plus;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone16Pro;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone16ProMax;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone16e;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone17;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone17Pro;
extern FBDeviceModel _Nonnull const FBDeviceModeliPhone17ProMax;

extern FBDeviceModel _Nonnull const FBDeviceModeliPodTouch_7thGeneration;

extern FBDeviceModel _Nonnull const FBDeviceModeliPad2;
extern FBDeviceModel _Nonnull const FBDeviceModeliPad_6thGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPad_7thGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPad_8thGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPad_9thGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPad_10thGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadRetina;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadA16;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadAir;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadAir2;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadAir_3rdGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadAir_4thGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro_9_7_Inch;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro_12_9_Inch;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro_9_7_Inch_2ndGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro_12_9_Inch_2ndGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro_12_9_Inch_3rdGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro_12_9_Inch_4thGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro_10_5_Inch;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro_11_Inch_1stGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro_12_9nch_1stGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadPro_11_Inch_2ndGeneration;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadMini_2;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadMini_3;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadMini_4;
extern FBDeviceModel _Nonnull const FBDeviceModeliPadMini_5;

extern FBDeviceModel _Nonnull const FBDeviceModelAppleTV;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleTV4K;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleTV4KAt1080p;

extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatch38mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatch42mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSE_40mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSE_44mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSeries2_38mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSeries2_42mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSeries3_38mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSeries3_42mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSeries4_40mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSeries4_44mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSeries5_40mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSeries5_44mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSeries6_40mm;
extern FBDeviceModel _Nonnull const FBDeviceModelAppleWatchSeries6_44mm;

/**
 OS Versions Name Enumeration.
 */
typedef NSString *FBOSVersionName NS_STRING_ENUM;

extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_7_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_8_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_8_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_8_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_8_3;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_8_4;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_9_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_9_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_9_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_9_3;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_9_3_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_9_3_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_10_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_10_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_10_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_10_3;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_11_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_11_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_11_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_11_3;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_11_4;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_12_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_12_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_12_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_12_4;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_13_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_13_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_13_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_13_3;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_13_4;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_13_5;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_14_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_14_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_14_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_15_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_15_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_15_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_15_3;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_15_4;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_15_5;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_16_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_16_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_16_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_16_3;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_16_4;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_16_5;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_16_6;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_16_7;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_17_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_17_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_17_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_17_3;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_17_4;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_17_5;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_17_6;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_17_7;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_18_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_18_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_18_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_18_3;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_18_4;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_18_5;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_18_6;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_18_7;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_26_0;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_26_1;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_26_2;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_26_3;
extern FBOSVersionName _Nonnull const FBOSVersionNameiOS_26_4;

extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_9_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_9_1;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_9_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_10_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_10_1;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_10_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_11_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_11_1;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_11_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_11_3;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_11_4;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_12_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_12_1;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_12_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_12_4;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_13_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_13_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_13_3;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_13_4;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_14_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_14_1;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_14_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_14_3;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_14_4;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_14_5;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_14_6;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_14_7;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_15_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_15_1;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_15_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_15_3;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_15_4;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_15_5;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_15_6;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_16_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_16_1;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_16_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_16_3;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_16_4;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_16_5;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_16_6;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_17_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_17_1;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_17_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_17_3;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_17_4;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_17_5;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_17_6;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_18_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_18_1;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_18_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_18_3;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_18_4;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_18_5;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_18_6;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_26_0;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_26_1;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_26_2;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_26_3;
extern FBOSVersionName _Nonnull const FBOSVersionNametvOS_26_4;

extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_2_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_2_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_2_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_3_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_3_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_3_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_4_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_4_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_4_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_5_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_5_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_5_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_5_3;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_6_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_6_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_6_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_7_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_7_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_7_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_7_3;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_7_4;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_7_5;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_7_6;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_8_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_8_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_8_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_8_3;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_8_4;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_8_5;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_8_6;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_8_7;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_8_8;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_9_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_9_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_9_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_9_3;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_9_4;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_9_5;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_9_6;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_10_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_10_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_10_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_10_3;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_10_4;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_10_5;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_10_6;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_11_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_11_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_11_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_11_3;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_11_4;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_11_5;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_11_6;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_26_0;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_26_1;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_26_2;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_26_3;
extern FBOSVersionName _Nonnull const FBOSVersionNamewatchOS_26_4;

extern FBOSVersionName _Nonnull const FBOSVersionNamemac;

#import <FBControlCore/FBControlCore-SwiftImport.h>
