//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import <CoreSimulator/SimPasteboard-Protocol.h>

@class NSArray, SimDevice, SimDeviceNotificationManager, SimDevicePasteboardConnection, SimMachPortServer;
@protocol OS_dispatch_queue;

@interface SimDevicePasteboard : NSObject <SimPasteboard>
{
    NSObject<OS_dispatch_queue> *_itemsQueue;
    unsigned long long _changeCount;
    NSArray *_items;
    SimDevice *_device;
    SimDevicePasteboardConnection *_pasteboardConnection;
    SimMachPortServer *_notificationServer;
    SimDeviceNotificationManager *_notificationManager;
    unsigned long long _registeredID;
    SimMachPortServer *_promisedDataServer;
    NSArray *_stagedItems;
}

@property (atomic, copy) NSArray *stagedItems;
@property (retain, nonatomic) SimMachPortServer *promisedDataServer;
@property (nonatomic, assign) unsigned long long registeredID;
@property (retain, nonatomic) SimDeviceNotificationManager *notificationManager;
@property (retain, nonatomic) SimMachPortServer *notificationServer;
@property (retain, nonatomic) SimDevicePasteboardConnection *pasteboardConnection;
@property (nonatomic, assign) __weak SimDevice *device;
@property (atomic, copy) NSArray *items;
@property (atomic, assign) unsigned long long changeCount; // @synthesize changeCount=_changeCount;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *itemsQueue;
- (void).cxx_destruct;
- (BOOL)unregisterNotificationHandler:(unsigned long long)arg1 error:(id *)arg2;
- (unsigned long long)registerNotificationHandlerOnQueue:(id)arg1 handler:(CDUnknownBlockType)arg2;
- (unsigned long long)registerNotificationHandler:(CDUnknownBlockType)arg1;
- (void)syncBarrier;
- (unsigned long long)setPasteboardWithItems:(id)arg1 error:(id *)arg2;
- (void)setPasteboardAsyncWithItems:(id)arg1 completionQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)itemsFromPasteboardWithTypes:(id)arg1 error:(id *)arg2;
- (void)itemsFromPasteboardAsyncWithTypes:(id)arg1 completionQueue:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)generateSimPasteboardItemsWithTypes:(id)arg1 changeCount:(unsigned long long)arg2;
- (void)setItems:(id)arg1 changeCount:(unsigned long long)arg2;
- (void)pasteboardHasChanged:(unsigned long long)arg1 itemsTypes:(id)arg2;
- (void)unsubscribe;
- (void)subscribe;
- (id)description;
- (void)registerSimDeviceNotificationListener;
- (void)dealloc;
- (id)initWithDevice:(id)arg1;

@end
