//
//     Generated by class-dump 3.5 (64 bit)
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, NSUUID, SimDevice, SimServiceContext;

@interface SimDevicePair : NSObject
{
    NSUUID *_UUID;
    SimDevice *_gizmo;
    SimDevice *_companion;
    NSString *_setPath;
    SimServiceContext *_serviceContext;
}

+ (id)SimDevicePairWithUUID:(id)arg1 gizmo:(id)arg2 companion:(id)arg3 serviceContext:(id)arg4 setPath:(id)arg5;
@property(retain) SimServiceContext *serviceContext; // @synthesize serviceContext=_serviceContext;
@property(copy) NSString *setPath; // @synthesize setPath=_setPath;
@property(retain) SimDevice *companion; // @synthesize companion=_companion;
@property(retain) SimDevice *gizmo; // @synthesize gizmo=_gizmo;
@property(copy) NSUUID *UUID; // @synthesize UUID=_UUID;
- (void).cxx_destruct;
- (id)newDevicePairNotification;
- (long long)compare:(id)arg1;
- (id)description;
- (void)invalidate;
- (id)initWithUUID:(id)arg1 gizmo:(id)arg2 companion:(id)arg3 serviceContext:(id)arg4 setPath:(id)arg5;
- (id)init;

@end

