//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface SimLocalThrowable : NSObject
{
    id _data;
}

+ (id)throwableWithData:(id)arg1;
@property (retain, nonatomic) id data;
- (void).cxx_destruct;
- (id)initWithData:(id)arg1;
- (id)init;

@end
