//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Feb 20 2016 22:04:40).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMachPort, NSString;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface SimMachPortServer : NSObject
{
    NSMachPort *_port;
    NSString *_name;
    NSObject<OS_dispatch_queue> *_serverQueue;
    NSObject<OS_dispatch_source> *_serverSource;
}

@property (retain, nonatomic) NSObject<OS_dispatch_source> *serverSource;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *serverQueue;
@property (nonatomic, copy, readonly) NSString *name;
@property (readonly, retain, nonatomic) NSMachPort *port;
- (void).cxx_destruct;
- (id)description;
- (id)initWithName:(id)arg1 machMessageHandler:(CDUnknownFunctionPointerType)arg2 machMessageSize:(unsigned int)arg3 error:(id *)arg4;

@end
